// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrestamoBancario.Infraestructure.Persistence;

#nullable disable

namespace PrestamoBancario.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908035033_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrestamoBancario.Domain.Entities.Prestamo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUsuarioModificacion")
                        .HasColumnType("bigint");

                    b.Property<int>("Tiempo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioModificacion");

                    b.HasIndex("IdUsuario", "FechaCreacion");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("PrestamoBancario.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Constrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PrestamoBancario.Domain.Entities.Prestamo", b =>
                {
                    b.HasOne("PrestamoBancario.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany("PrestamosCreados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrestamoBancario.Domain.Entities.Usuario", "UsuarioModificacion")
                        .WithMany("PrestamosModificados")
                        .HasForeignKey("IdUsuarioModificacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PrestamoBancario.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PrestamosCreados");

                    b.Navigation("PrestamosModificados");
                });
#pragma warning restore 612, 618
        }
    }
}
